// <auto-generated />
namespace Together.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ReNewedarchitecturewithidentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReNewedarchitecturewithidentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201703021612000_ReNewed architecture with identity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
