// <auto-generated />
namespace Together.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addedpassengersandroutenewfields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedpassengersandroutenewfields));
        
        string IMigrationMetadata.Id
        {
            get { return "201908061030372_Added passengers and route new fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
